supabase sql :
-- Buat tabel categories dulu
CREATE TABLE categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama text NOT NULL UNIQUE,
  deskripsi text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Lalu products (karena ada FK ke categories)
CREATE TABLE products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kategori_id bigint REFERENCES categories(id),
  nama text NOT NULL,
  harga decimal(10,2) NOT NULL,
  stok int NOT NULL DEFAULT 0,
  gambar_url text,
  tanggal_kadaluarsa timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Users
CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  password text NOT NULL,
  peran text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Transactions
CREATE TABLE transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint REFERENCES users(id),
  total_bayar decimal(10,2) NOT NULL,
  metode_pembayaran text NOT NULL,
  status text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Transaction Items
CREATE TABLE transaction_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaksi_id bigint REFERENCES transactions(id),
  produk_id bigint REFERENCES products(id),
  jumlah int NOT NULL,
  harga_saat_ini decimal(10,2) NOT NULL,
  subtotal decimal(10,2) NOT NULL
);
